#!/bin/sh
set -e

board=$(strings /proc/device-tree/compatible | head -1)

find_mtd_index() {
	local PART="$(grep "\"$1\"" /proc/mtd | awk -F: '{print $1}')"
	local INDEX="${PART##mtd}"

	echo ${INDEX}
}

find_mtd_part() {
	local INDEX=$(find_mtd_index "$1")
	local PREFIX=/dev/mtdblock

	[ -d /dev/mtdblock ] && PREFIX=/dev/mtdblock/
	echo "${INDEX:+$PREFIX$INDEX}"
}

find_mtd_chardev() {
	local INDEX=$(find_mtd_index "$1")
	local PREFIX=/dev/mtd

	[ -d /dev/mtd ] && PREFIX=/dev/mtd/
	echo "${INDEX:+$PREFIX$INDEX}"
}

caldata_die() {
	echo "caldata: " "$*"
	exit 1
}

caldata_extract() {
	local part=$1
	local offset=$(($2))
	local count=$(($3))
	local mtd

	mtd=$(find_mtd_chardev $part)
	[ -n "$mtd" ] || caldata_die "no mtd device found for partition $part"

	dd if=$mtd of=/lib/firmware/$FIRMWARE iflag=skip_bytes bs=$count skip=$offset count=1 2>/dev/null || \
		caldata_die "failed to extract calibration data from $mtd"
}

FIRMWARE="ath11k/IPQ8074/hw2.0/cal-ahb-c000000.wifi.bin"
case "$board" in
	qnap,301w|\
	xiaomi,ax9000)
		caldata_extract "0:art" 0x1000 0x20000
		;;
	*)
		echo "Unsupported board:" $board
		exit 1
	;;
esac

FIRMWARE="ath11k/QCN9074/hw1.0/cal-pci-0000:01:00.0.bin"
case "$board" in
        xiaomi,ax9000)
		caldata_extract "0:art" 0x26800 0x20000
		;;
	*)
		echo "Unsupported board:" $board
		exit 1
	;;
esac